version: '3'
services:
  manager:
    build:
      context: .
    ports:
      - 37259:37259
    networks:
      - network1
    links:
      - trainer
    environment:
      - 'dockerfile: manager.dockerfile'
    volumes:
      - manager:/home/dorneles/docker_volumes/manager
  trainer:
    environment:
      - 'MANAGER_HOST: manager'
      - 'dockerfile: trainer.dockerfile'
    build:
      context: .
    ports:
      - "37259:37259"
    links:
      - manager
    networks:
      - network1
    depends_on:
      - manager
    volumes:
      - trainer:/home/dorneles/docker_volumes/trainer
networks:
  network1:
    driver: bridge

volumes:
  - manager:
  - trainer: